//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenamhiWebForm2.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioSenamhiSoap")]
    public interface ServicioSenamhiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listarlugares", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listarlugares();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listarlugares", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarlugaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaLocalidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaLocalidad(string TNombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaLocalidad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaLocalidadAsync(string TNombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSenamhiSoapChannel : SenamhiWebForm2.ServiceReference1.ServicioSenamhiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSenamhiSoapClient : System.ServiceModel.ClientBase<SenamhiWebForm2.ServiceReference1.ServicioSenamhiSoap>, SenamhiWebForm2.ServiceReference1.ServicioSenamhiSoap {
        
        public ServicioSenamhiSoapClient() {
        }
        
        public ServicioSenamhiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSenamhiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSenamhiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSenamhiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listarlugares() {
            return base.Channel.Listarlugares();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarlugaresAsync() {
            return base.Channel.ListarlugaresAsync();
        }
        
        public System.Data.DataSet ListaLocalidad(string TNombre) {
            return base.Channel.ListaLocalidad(TNombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaLocalidadAsync(string TNombre) {
            return base.Channel.ListaLocalidadAsync(TNombre);
        }
    }
}
